---
- name: Deploy Production Stack
  hosts: production
  become: yes
  gather_facts: yes

  vars_files:
    - vault/secrets.yml

  vars:
    app_dir: /opt/app
    db_password: "{{ vault_db_password }}"
    redis_password: "{{ vault_redis_password }}"

  pre_tasks:
    - name: Update and upgrade packages
      # Fix 2 : apt instead of package_manager for ubuntu.
      apt:
        update_cache: yes
        upgrade: dist

    - name: Create application user
      # Fix 3 : update add_user to ansible.builtin.user
      ansible.builtin.user:
        name: appuser
        system: true
        create_home: false
        shell: /bin/bash

  tasks:
    - name: Install Docker dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
        state: present

    #Fix 5 : GPG keys are using old approach and apt_key is now depreciated & giving error so, I have to changed the approach to new keyring approach where Adding GPG Key and Adding docker repository command changes to modern keyring approach.

    - name: Download Docker GPG key
      ansible.builtin.get_url:
        url: "https://download.docker.com/linux/ubuntu/gpg"  # Direct URL to public key
        dest: "/etc/apt/trusted.gpg.d/docker-ce.gpg"  # Keyring file path
        mode: '0644'  # Required permissions (read/write for root, read for others)
        owner: appuser
        group: appuser
 
    - name: Add Docker repository to sources.list.d
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: "docker-ce"  # Creates /etc/apt/sources.list.d/docker-ce.list
        update_cache: true  # Run `apt update` after adding

    - name: Install Docker and Docker Compose
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present

    - name: Create application directory
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: appuser
        group: appuser

    - name: Copy Docker Compose file
      template:
        src: ../templates/docker-compose.yml.j2
        dest: "{{ app_dir }}/docker-compose.yml"

    - name: Copy .env file with secrets (Ansible Vault)
      copy:
        content: |
          DB_PASSWORD={{ db_password }}
          REDIS_PASSWORD={{ redis_password }}
        dest: "{{ app_dir }}/.env"
      notify: Restart docker stack

    - name: Install Python Docker SDK
      become: true
      ansible.builtin.apt:
        name: python3-docker
        state: present
        update_cache: true

    - name: Start Docker Compose stack as appuser
      ansible.builtin.command:
        cmd: sudo -u appuser docker compose up -d
        chdir: "{{ app_dir }}"
      become: true

    - name: Configure firewall (ufw)
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - 22
        - 80
        - 443

  handlers:
    - name: Restart docker stack
      ansible.builtin.shell:
        cmd: sudo -u appuser docker compose down && sudo -u appuser docker compose up -d
        chdir: "{{ app_dir }}"
