[production]
app-server ansible_host=44.250.47.231 ansible_user=ubuntu

#Fix 1 : update ansible inventory file ip address and user's name and ssh key file

[production:vars]
ansible_ssh_private_key_file=/home/runner/.ssh/test-node-1-key.pem
ansible_python_interpreter=/usr/bin/python3
