name: Broken CI/CD Pipeline

on:
  push:
    #Fix 2 (optional) : change push/pull_req branch in workflow call.
    branches: [final_fix]
  pull_request:
    branches: [final_fix]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      #Fix 3: Install dependencies for user-service and order service.
      - name: Install dependencies
        run: |
          cd user-service && pip install --no-cache-dir -r requirements.txt
          cd ../order-service && pip install --no-cache-dir -r requirements.txt


      - name: Run Python tests
        run: |
          cd user-service && pytest
          cd ../order-service && pytest

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to production
        run: |
          cd infrastructure
          ansible-playbook -i ansible/inventory.ini ansible/deploy.yml
        env:
          ANSIBLE_VAULT_PASSWORD: mysecretpassword
