name: Broken CI/CD Pipeline

on:
  push:
    #Fix 2 (optional) : change push/pull_req branch in workflow call.
    branches: [final_fix]
  pull_request:
    branches: [final_fix]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      #Fix 3: Install dependencies for user-service and order service.
      - name: Install dependencies
        run: |
          cd user-service && pip install --no-cache-dir -r requirements.txt
          cd ../order-service && pip install --no-cache-dir -r requirements.txt


      - name: Run Python tests
        run: |
          cd user-service && pytest
          cd ../order-service && pytest

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: build
        run: |
          docker compose up -d

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/test-node-1-key.pem
          chmod 600 ~/.ssh/test-node-1-key.pem

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 44.250.47.231 >> ~/.ssh/known_hosts

      - name: Configure Ansible Vault password
        run: |
          printf '%s\n' "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > infrastructure/ansible/vault-pass.txt
          chmod 600 infrastructure/ansible/vault-pass.txt

      - name: Deploy to production
        run: |
          cd infrastructure
          ansible-playbook -i ansible/inventory.ini ansible/deploy.yml --vault-password-file ansible/vault-pass.txt
        env:
          ANSIBLE_VAULT_PASSWORD: mysecretpassword
